export {default as BlogPage} from './blog/blogs'
export {default as CustomTabPanelAuth} from './auth/login-modal'
export {default as MainButton} from './button/button'
export {default as BlogsSection} from './home/blog/blog'
export {default as TrendsSection} from './home/blog/trends'
export {default as FooterContact} from './home/footer/contact'
export {default as FooterHeader} from './home/footer/footer-header'
export {default as Footer} from './home/footer/footer'
export {default as Navbar} from './home/navbar/navbar'
export {default as Hero} from './home/hero/hero'
export {default as Slider} from './slider/slider'
export {default as CategoriesSection} from './home/cards/categories'
export {default as ProfileSection} from './profile/profile'
export {default as AccountDetails} from './profile/account-details'
export {default as Address} from './profile/address'
export {default as MyProducts} from './profile/my-products'
export {default as Profile} from './profile/profile'
export {default as Wishlist} from './profile/wishlist'
export {default as TrackOrder} from './profile/track-order'


